[package]
name = "crawly"
version = "0.1.0"
authors = ["Senthil V Kumar <me@senthilvkumar.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
